"use client";

import { AlertTriangle, Banknote, CalendarClock, Check, CircleDollarSign, Plus, ReceiptText, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type PaymentStatus = "PENDING" | "PAID" | "OVERDUE" | "CANCELLED";
type CommissionStatus = "PENDING" | "PAID" | "CANCELLED";
type FinanceData = {
  summary: { totalValue: number; received: number; pending: number; nextDueDate: string | null; overdueCount: number; overdueAmount: number };
  payments: Array<{ id: string; description: string; amount: number; dueDate: string; paidAt: string | null; status: PaymentStatus; notes: string | null }>;
  commissions: Array<{ id: string; userId: string; userName: string; percentage: number; amount: number; status: CommissionStatus }>;
  members: Array<{ id: string; name: string; role: string }>;
};
const paymentLabels: Record<PaymentStatus, string> = { PENDING: "Pendente", PAID: "Recebido", OVERDUE: "Atrasado", CANCELLED: "Cancelado" };
const commissionLabels: Record<CommissionStatus, string> = { PENDING: "Pendente", PAID: "Paga", CANCELLED: "Cancelada" };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const date = (value: string | null) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "—";
async function requestFinance(showId: string) { const response = await fetch(`/api/shows/${showId}/finance`), data = await response.json() as FinanceData & { error?: string }; return { response, data }; }

export function ShowFinance({ showId }: { showId: string }) {
  const [data, setData] = useState<FinanceData | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [paymentOpen, setPaymentOpen] = useState(false), [commissionOpen, setCommissionOpen] = useState(false);
  const [payment, setPayment] = useState({ description: "", amount: "", dueDate: "", notes: "" }), [commission, setCommission] = useState({ userId: "", percentage: "" });
  const load = useCallback(async () => { const { response, data } = await requestFinance(showId); if (response.ok) setData(data); else setMessage(data.error || "Não foi possível carregar o financeiro."); }, [showId]);
  useEffect(() => { let mounted = true; requestFinance(showId).then(({ response, data }) => { if (!mounted) return; if (response.ok) setData(data); else setMessage(data.error || "Não foi possível carregar o financeiro."); }); return () => { mounted = false; }; }, [showId]);
  async function post(body: Record<string, unknown>) { setBusy(true); setMessage(""); const response = await fetch(`/api/shows/${showId}/finance`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setMessage(result.error || "Não foi possível salvar."); return false; } await load(); return true; }
  async function patch(body: Record<string, unknown>) { setBusy(true); setMessage(""); const response = await fetch(`/api/shows/${showId}/finance`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }), result = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setMessage(result.error || "Não foi possível atualizar."); return; } await load(); }
  async function createPayment(event: React.FormEvent) { event.preventDefault(); const amount = Math.round(Number(payment.amount.replace(",", ".")) * 100); if (await post({ entity: "payment", ...payment, amount })) { setPayment({ description: "", amount: "", dueDate: "", notes: "" }); setPaymentOpen(false); setMessage("Parcela criada."); } }
  async function createCommission(event: React.FormEvent) { event.preventDefault(); if (await post({ entity: "commission", userId: commission.userId, percentage: Number(commission.percentage.replace(",", ".")) })) { setCommission({ userId: "", percentage: "" }); setCommissionOpen(false); setMessage("Comissão criada."); } }
  if (!data) return <section className="show-finance finance-loading">{message || "Carregando financeiro…"}</section>;
  return <section className="show-finance"><div className="section-heading finance-heading"><div><p className="eyebrow">Financeiro operacional</p><h2>Recebimentos e comissão</h2><p>Acompanhamento do valor contratado sem rotinas contábeis.</p></div><div><button className="button button-secondary" onClick={() => setCommissionOpen(value => !value)}><CircleDollarSign />Comissão</button><button className="button button-primary" onClick={() => setPaymentOpen(value => !value)}><Plus />Nova parcela</button></div></div>{message && <div className={message.includes("criada") ? "notice" : "calendar-alert"}>{message}</div>}
    <div className="finance-summary"><Summary icon={<Banknote />} label="Valor total" value={money(data.summary.totalValue)} /><Summary icon={<Check />} label="Total recebido" value={money(data.summary.received)} tone="success" /><Summary icon={<ReceiptText />} label="Total pendente" value={money(data.summary.pending)} /><Summary icon={<CalendarClock />} label="Próximo vencimento" value={date(data.summary.nextDueDate)} tone={data.summary.overdueCount ? "danger" : undefined} /></div>
    {data.summary.overdueCount > 0 && <div className="finance-overdue"><AlertTriangle /><div><b>{data.summary.overdueCount} {data.summary.overdueCount === 1 ? "pagamento atrasado" : "pagamentos atrasados"}</b><span>{money(data.summary.overdueAmount)} aguardando recebimento.</span></div></div>}
    {paymentOpen && <form className="finance-form" onSubmit={createPayment}><header><div><p className="eyebrow">Nova parcela</p><h3>Programar recebimento</h3></div><button type="button" className="icon-close" onClick={() => setPaymentOpen(false)}><X /></button></header><div className="form-row"><label>Descrição<input required value={payment.description} onChange={event => setPayment(current => ({ ...current, description: event.target.value }))} placeholder="Ex.: Sinal de 50%" /></label><label>Valor (R$)<input required inputMode="decimal" value={payment.amount} onChange={event => setPayment(current => ({ ...current, amount: event.target.value }))} placeholder="0,00" /></label></div><div className="form-row"><label>Vencimento<input required type="date" value={payment.dueDate} onChange={event => setPayment(current => ({ ...current, dueDate: event.target.value }))} /></label><label>Observações<input value={payment.notes} onChange={event => setPayment(current => ({ ...current, notes: event.target.value }))} /></label></div><button className="button button-primary" disabled={busy}>Criar parcela</button></form>}
    {commissionOpen && <form className="finance-form" onSubmit={createCommission}><header><div><p className="eyebrow">Comissão comercial</p><h3>Associar ao show</h3></div><button type="button" className="icon-close" onClick={() => setCommissionOpen(false)}><X /></button></header><div className="form-row"><label>Comercial<select required value={commission.userId} onChange={event => setCommission(current => ({ ...current, userId: event.target.value }))}><option value="">Selecione</option>{data.members.map(member => <option key={member.id} value={member.id}>{member.name} · {member.role}</option>)}</select></label><label>Percentual (%)<input required inputMode="decimal" value={commission.percentage} onChange={event => setCommission(current => ({ ...current, percentage: event.target.value }))} placeholder="10" /></label></div><button className="button button-primary" disabled={busy}>Criar comissão</button></form>}
    <div className="finance-columns"><section><div className="finance-subhead"><h3>Pagamentos</h3><span className="count-badge">{data.payments.length}</span></div><div className="finance-list">{data.payments.map(item => <article className="payment-row" key={item.id}><div><b>{item.description}</b><small>Vence em {date(item.dueDate)}{item.paidAt ? ` · recebido em ${new Date(item.paidAt).toLocaleDateString("pt-BR")}` : ""}</small></div><strong>{money(item.amount)}</strong><span className={`finance-status finance-${item.status.toLowerCase()}`}>{paymentLabels[item.status]}</span>{["PENDING", "OVERDUE"].includes(item.status) && <div className="finance-row-actions"><button disabled={busy} onClick={() => patch({ entity: "payment", id: item.id, status: "PAID" })}>Marcar recebido</button><button disabled={busy} onClick={() => patch({ entity: "payment", id: item.id, status: "CANCELLED" })}>Cancelar</button></div>}</article>)}{!data.payments.length && <p className="finance-empty">Nenhuma parcela cadastrada.</p>}</div></section><section><div className="finance-subhead"><h3>Comissões</h3><span className="count-badge">{data.commissions.length}</span></div><div className="finance-list">{data.commissions.map(item => <article className="commission-row" key={item.id}><div><b>{item.userName}</b><small>{item.percentage.toLocaleString("pt-BR")}% do valor do show</small></div><strong>{money(item.amount)}</strong><span className={`finance-status finance-${item.status.toLowerCase()}`}>{commissionLabels[item.status]}</span>{item.status === "PENDING" && <div className="finance-row-actions"><button disabled={busy} onClick={() => patch({ entity: "commission", id: item.id, status: "PAID" })}>Marcar paga</button><button disabled={busy} onClick={() => patch({ entity: "commission", id: item.id, status: "CANCELLED" })}>Cancelar</button></div>}</article>)}{!data.commissions.length && <p className="finance-empty">Nenhuma comissão associada.</p>}</div></section></div>
  </section>;
}
function Summary({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone?: string }) { return <article className={`finance-metric ${tone || ""}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
