"use client";
import { useCallback, useEffect, useState } from "react";

type Org = { id:string; name:string; slug:string; email:string; phone?:string; document?:string; website?:string; instagram?:string; logo?:string; role:string };
type Member = { id:string; name:string; email:string; role:string; status:string };
const blank = { name:"", email:"", phone:"", document:"", website:"", instagram:"", logo:"" };

export function BookStageApp({ user, isDevelopment }:{user:{id:string;email:string;name:string};isDevelopment:boolean}) {
  const [organizations,setOrganizations]=useState<Org[]>([]); const [active,setActive]=useState<Org|null>(null); const [members,setMembers]=useState<Member[]>([]);
  const [editing,setEditing]=useState(false); const [form,setForm]=useState(blank); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{ const r=await fetch("/api/organizations"); const d=await r.json() as {organizations?:Org[]}; setOrganizations(d.organizations||[]); setLoading(false); },[]);
  useEffect(()=>{fetch("/api/organizations").then(r=>r.json() as Promise<{organizations?:Org[]}>).then(d=>{setOrganizations(d.organizations||[]);setLoading(false)})},[]);
  useEffect(()=>{if(active) fetch(`/api/organizations/${active.id}/members`).then(r=>r.json() as Promise<{members?:Member[]}>).then(d=>setMembers(d.members||[]))},[active]);
  async function save(e:React.FormEvent){e.preventDefault(); const url=editing&&active?`/api/organizations/${active.id}`:"/api/organizations"; const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json() as {error?:string;organization?:Org};if(!r.ok){setNotice(d.error||"Não foi possível salvar.");return}setNotice(editing?"Organização atualizada.":"Organização criada.");setEditing(false);setForm(blank);await load();if(d.organization) await choose(d.organization);}
  async function choose(org:Org){const r=await fetch("/api/active-organization",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:org.id})});if(r.ok){setActive(org);setNotice("")}}
  function edit(){if(!active)return;setForm({name:active.name,email:active.email,phone:active.phone||"",document:active.document||"",website:active.website||"",instagram:active.instagram||"",logo:active.logo||""});setEditing(true)}
  async function switchUser(id:string){await fetch("/api/dev-user",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:id})});location.reload()}
  if(loading)return <main className="center"><div className="loading">Preparando seu ambiente…</div></main>;
  if(!organizations.length||editing)return <Onboarding form={form} setForm={setForm} save={save} editing={editing} cancel={()=>setEditing(false)} notice={notice}/>;
  return <div className="shell">
    <aside><div className="logo"><span className="brand-mark">B</span><b>BookStage</b></div><nav><button className="nav-active">▦ <span>Visão geral</span></button><button>♙ <span>Equipe</span></button><div className="soon">Próximos módulos</div>{["Artistas","Catálogo","Agenda","CRM","Contratos","Produção","Financeiro"].map(x=><button disabled key={x}><span>{x}</span><small>Em breve</small></button>)}</nav><div className="user"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.email}</small></div></div></aside>
    <main className="workspace"><header><div><small>ORGANIZAÇÃO ATIVA</small><select aria-label="Organização ativa" value={active?.id||""} onChange={e=>choose(organizations.find(o=>o.id===e.target.value)!)}><option value="" disabled>Selecione uma organização</option>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div><button className="outline" onClick={()=>{setForm(blank);setEditing(true)}}>+ Nova organização</button></header>
    {!active?<section className="empty"><div className="stage-icon">◫</div><p className="eyebrow">FUNDAÇÃO PRONTA</p><h1>Seu palco operacional<br/>começa por aqui.</h1><p>Escolha a organização ativa para acessar o ambiente isolado da sua equipe.</p><div className="org-grid">{organizations.map(o=><button key={o.id} onClick={()=>choose(o)}><span>{o.name[0]}</span><b>{o.name}</b><small>{o.role}</small></button>)}</div></section>:
    <><section className="welcome"><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, {user.name.split(" ")[0]}.</h1><p>A fundação de <b>{active.name}</b> está pronta. Os próximos módulos entrarão aqui, no tempo certo.</p></div><button className="outline" onClick={edit}>Editar organização</button></section><section className="cards"><article><small>STATUS DO AMBIENTE</small><strong><i/> Ativo</strong><p>Dados isolados e protegidos por organização.</p></article><article><small>EQUIPE</small><strong>{members.length.toString().padStart(2,"0")}</strong><p>{members.length===1?"pessoa com acesso":"pessoas com acesso"}</p></article><article><small>SEU PERFIL</small><strong>{active.role}</strong><p>Permissões aplicadas no servidor.</p></article></section><section className="team"><div><p className="eyebrow">EQUIPE E ACESSOS</p><h2>Quem está neste ambiente</h2></div>{members.map(m=><div className="member" key={m.id}><div className="avatar">{m.name[0]}</div><div><b>{m.name}</b><small>{m.email}</small></div><span>{m.role}</span><em>{m.status}</em></div>)}<p className="hint">Convites e gestão avançada de usuários serão habilitados em uma etapa futura.</p></section></>}
    {isDevelopment&&<div className="dev-switch">Teste local: <button onClick={()=>switchUser("user-a")}>Usuário A</button><button onClick={()=>switchUser("user-b")}>Usuário B</button></div>}</main></div>
}

function Onboarding({form,setForm,save,editing,cancel,notice}:{form:typeof blank;setForm:(x:typeof blank)=>void;save:(e:React.FormEvent)=>void;editing:boolean;cancel:()=>void;notice:string}){const field=(key:keyof typeof blank,label:string,placeholder="")=><label>{label}<input value={form[key]} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;return <main className="onboarding"><section className="onboard-copy"><div className="logo"><span className="brand-mark">B</span><b>BookStage</b></div><p className="eyebrow">{editing?"CONFIGURAÇÕES":"PRIMEIRO PASSO"}</p><h1>{editing?"Ajuste os dados da organização.":"Vamos preparar seu ambiente."}</h1><p>Essa organização será o espaço seguro e isolado onde sua operação de shows vai acontecer.</p><div className="trust">✓ Isolamento por organização<br/>✓ Perfis e permissões no servidor<br/>✓ Base pronta para crescer</div></section><form onSubmit={save}><p className="step">DADOS DA ORGANIZAÇÃO</p><h2>{editing?"Editar organização":"Crie sua organização"}</h2>{notice&&<div className="notice">{notice}</div>}{field("name","Nome da organização *","Ex.: Aurora Produções")}{field("email","E-mail comercial *","contato@empresa.com.br")}<div className="row">{field("phone","Telefone","(11) 99999-9999")}{field("document","CNPJ (opcional)","00.000.000/0001-00")}</div>{field("website","Website","https://")}{field("instagram","Instagram","@suaempresa")}{field("logo","URL do logo","https://...")}<div className="actions">{editing&&<button type="button" className="outline" onClick={cancel}>Cancelar</button>}<button className="primary">{editing?"Salvar alterações":"Criar meu ambiente →"}</button></div></form></main>}
