"use client";

import { Building2, CalendarDays, ChevronDown, CircleDollarSign, FileText, Handshake, LayoutDashboard, Menu, Music2, Plus, Settings2, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Org = { id:string; name:string; slug:string; email:string; phone?:string; document?:string; website?:string; instagram?:string; logo?:string; role:string };
type Member = { id:string; name:string; email:string; role:string; status:string };
const blank = { name:"", email:"", phone:"", document:"", website:"", instagram:"", logo:"" };
const futureModules = [["Artistas",Music2],["Catálogo",Sparkles],["Agenda",CalendarDays],["CRM",Handshake],["Contratos",FileText],["Produção",Settings2],["Financeiro",CircleDollarSign]] as const;

function Brand(){return <div className="brand"><span className="brand-mark">B<span/></span><b>BookStage</b></div>}

export function BookStageApp({user,isDevelopment}:{user:{id:string;email:string;name:string};isDevelopment:boolean}){
  const [organizations,setOrganizations]=useState<Org[]>([]),[active,setActive]=useState<Org|null>(null),[members,setMembers]=useState<Member[]>([]);
  const [editing,setEditing]=useState(false),[formOpen,setFormOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/organizations"),d=await r.json() as {organizations?:Org[]};setOrganizations(d.organizations||[]);setLoading(false)},[]);
  useEffect(()=>{fetch("/api/organizations").then(r=>r.json() as Promise<{organizations?:Org[]}>).then(d=>{setOrganizations(d.organizations||[]);setLoading(false)})},[]);
  useEffect(()=>{if(active)fetch(`/api/organizations/${active.id}/members`).then(r=>r.json() as Promise<{members?:Member[]}>).then(d=>setMembers(d.members||[]))},[active]);
  async function save(e:React.FormEvent){e.preventDefault();const url=editing&&active?`/api/organizations/${active.id}`:"/api/organizations",r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json() as {error?:string;organization?:Org};if(!r.ok){setNotice(d.error||"Não foi possível salvar.");return}setNotice(editing?"Organização atualizada.":"Organização criada.");setEditing(false);setFormOpen(false);setForm(blank);await load();if(d.organization)await choose(d.organization)}
  async function choose(org:Org){const r=await fetch("/api/active-organization",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:org.id})});if(r.ok){setActive(org);setNotice("")}}
  function edit(){if(!active)return;setForm({name:active.name,email:active.email,phone:active.phone||"",document:active.document||"",website:active.website||"",instagram:active.instagram||"",logo:active.logo||""});setEditing(true);setFormOpen(true)}
  async function switchUser(id:string){await fetch("/api/dev-user",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:id})});location.reload()}
  if(loading)return <main className="center"><div className="loading"><span className="spinner"/>Preparando seu ambiente…</div></main>;
  if(!organizations.length||formOpen)return <Onboarding form={form} setForm={setForm} save={save} editing={editing} cancel={()=>{setEditing(false);setFormOpen(false)}} notice={notice}/>;
  return <div className="app-shell">
    <button className="mobile-menu-button" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu size={21}/></button>{menuOpen&&<button className="sidebar-backdrop" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}/>}
    <aside className={`sidebar ${menuOpen?"is-open":""}`}><div className="sidebar-head"><Brand/><button className="mobile-close" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}><X size={20}/></button></div><div className="sidebar-org"><div className="org-avatar">{active?.name[0]??organizations[0]?.name[0]}</div><div><small>Organização</small><strong>{active?.name??"Selecione o ambiente"}</strong></div><ChevronDown size={16}/></div><nav aria-label="Navegação principal"><button className="nav-active"><LayoutDashboard/><span>Visão geral</span></button><button><Users/><span>Equipe</span></button><p className="nav-label">Próximos módulos</p>{futureModules.map(([label,Icon])=><button disabled key={label}><Icon/><span>{label}</span><small>Em breve</small></button>)}</nav><div className="sidebar-user"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.email}</small></div></div></aside>
    <main className="workspace"><header className="topbar"><div className="org-picker"><small>Organização ativa</small><div><Building2 size={16}/><select aria-label="Organização ativa" value={active?.id||""} onChange={e=>choose(organizations.find(o=>o.id===e.target.value)!)}><option value="" disabled>Selecione uma organização</option>{organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div></div><button className="button button-secondary" onClick={()=>{setForm(blank);setEditing(false);setFormOpen(true)}}><Plus size={16}/>Nova organização</button></header>
    <div className="page-content">{!active?<section className="empty-state"><div className="empty-icon"><Building2/></div><p className="eyebrow">Fundação pronta</p><h1>Seu palco operacional começa por aqui.</h1><p>Escolha a organização ativa para acessar o ambiente isolado da sua equipe.</p><div className="org-grid">{organizations.map(o=><button key={o.id} onClick={()=>choose(o)}><span>{o.name[0]}</span><b>{o.name}</b><small>{o.role}</small></button>)}</div></section>:<><section className="page-heading"><div><p className="eyebrow">Visão geral</p><h1>Olá, {user.name.split(" ")[0]}.</h1><p>A fundação de <b>{active.name}</b> está pronta. Os próximos módulos entrarão aqui, no tempo certo.</p></div><button className="button button-secondary" onClick={edit}>Editar organização</button></section><section className="metric-grid"><article className="metric-card"><div className="metric-icon success"><ShieldCheck/></div><div><small>Status do ambiente</small><strong className="status-active"><i/>Ativo</strong><p>Dados isolados e protegidos por organização.</p></div></article><article className="metric-card"><div className="metric-icon"><Users/></div><div><small>Equipe</small><strong>{members.length.toString().padStart(2,"0")}</strong><p>{members.length===1?"pessoa com acesso":"pessoas com acesso"}</p></div></article><article className="metric-card"><div className="metric-icon accent"><ShieldCheck/></div><div><small>Seu perfil</small><strong>{active.role}</strong><p>Permissões aplicadas no servidor.</p></div></article></section><section className="team-card"><div className="section-heading"><div><p className="eyebrow">Equipe e acessos</p><h2>Quem está neste ambiente</h2></div><span className="count-badge">{members.length} {members.length===1?"membro":"membros"}</span></div><div className="member-table"><div className="table-head"><span>Membro</span><span>Perfil</span><span>Status</span></div>{members.map(m=><div className="member-row" key={m.id}><div className="member-person"><div className="avatar">{m.name[0]}</div><div><b>{m.name}</b><small>{m.email}</small></div></div><span className="role-badge">{m.role}</span><em className="status-badge">{m.status}</em></div>)}</div><p className="hint">Convites e gestão avançada de usuários serão habilitados em uma etapa futura.</p></section></>}</div>{isDevelopment&&<div className="dev-switch">Teste local:<button onClick={()=>switchUser("user-a")}>Usuário A</button><button onClick={()=>switchUser("user-b")}>Usuário B</button></div>}</main>
  </div>
}

function Onboarding({form,setForm,save,editing,cancel,notice}:{form:typeof blank;setForm:(x:typeof blank)=>void;save:(e:React.FormEvent)=>void;editing:boolean;cancel:()=>void;notice:string}){const field=(key:keyof typeof blank,label:string,placeholder="")=><label>{label}<input value={form[key]} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;return <main className="onboarding"><section className="onboard-intro"><Brand/><div><p className="eyebrow">{editing?"Configurações":"Primeiro passo"}</p><h1>{editing?"Ajuste os dados da organização.":"Vamos preparar seu ambiente."}</h1><p>Essa organização será o espaço seguro e isolado onde sua operação de shows vai acontecer.</p><ul><li><ShieldCheck/>Isolamento por organização</li><li><Users/>Perfis e permissões no servidor</li><li><LayoutDashboard/>Base pronta para crescer</li></ul></div><p className="product-line">Todo o modelo operacional de shows em um só lugar.</p></section><form className="organization-form" onSubmit={save}><div className="form-heading"><span className="form-step">01</span><div><p className="eyebrow">Dados da organização</p><h2>{editing?"Editar organização":"Crie sua organização"}</h2></div></div>{notice&&<div className="notice">{notice}</div>}{field("name","Nome da organização *","Ex.: Aurora Produções")}{field("email","E-mail comercial *","contato@empresa.com.br")}<div className="form-row">{field("phone","Telefone","(11) 99999-9999")}{field("document","CNPJ (opcional)","00.000.000/0001-00")}</div>{field("website","Website","https://")}{field("instagram","Instagram","@suaempresa")}{field("logo","URL do logo","https://...")}<div className="form-actions">{editing&&<button type="button" className="button button-secondary" onClick={cancel}>Cancelar</button>}<button className="button button-primary">{editing?"Salvar alterações":"Criar meu ambiente"}</button></div></form></main>}
