import { env } from "cloudflare:workers";
import { requireActiveMembership } from "@/app/lib/active-membership";
import { dashboardVisibility, dashboardWindow, normalizeDashboardPeriod } from "@/app/lib/dashboard-rules";

type CountRow = { count: number; total?: number | null };
export async function GET(request: Request) {
  const context = await requireActiveMembership(); if ("error" in context) return context.error;
  const url = new URL(request.url), period = normalizeDashboardPeriod(url.searchParams.get("period")), window = dashboardWindow(period), visibility = dashboardVisibility(context.membership.role), requestedArtist = url.searchParams.get("artist") || "", requestedCommercial = url.searchParams.get("commercial") || "";
  if (requestedArtist && !(await env.DB.prepare(`SELECT 1 FROM artists WHERE id=? AND organization_id=?`).bind(requestedArtist, context.organizationId).first())) return Response.json({ error: "Artista não encontrado." }, { status: 404 });
  if (requestedCommercial && visibility.commercialFilter && !(await env.DB.prepare(`SELECT 1 FROM memberships WHERE user_id=? AND organization_id=? AND status='ACTIVE' AND role IN ('OWNER','MANAGER','SALES')`).bind(requestedCommercial, context.organizationId).first())) return Response.json({ error: "Comercial não encontrado." }, { status: 404 });
  const artistId = requestedArtist || null, commercialId = context.membership.role === "SALES" ? context.user.id : visibility.commercialFilter && requestedCommercial ? requestedCommercial : null;
  const opportunityWhere = `opportunity.organization_id=? AND date(opportunity.created_at)>=? AND date(opportunity.created_at)<=?${artistId ? " AND opportunity.artist_id=?" : ""}${commercialId ? " AND opportunity.assigned_user_id=?" : ""}`;
  const opportunityBindings: unknown[] = [context.organizationId, window.commercialStart, window.commercialEnd, ...(artistId ? [artistId] : []), ...(commercialId ? [commercialId] : [])];
  const operationalBindings = [...(artistId ? [artistId] : []), ...(commercialId ? [commercialId] : [])];
  const artists = await env.DB.prepare(`SELECT id,name FROM artists WHERE organization_id=? AND status='ACTIVE' ORDER BY name`).bind(context.organizationId).all(), commercials = visibility.commercialFilter ? await env.DB.prepare(`SELECT user.id,user.name,membership.role FROM memberships membership JOIN users user ON user.id=membership.user_id WHERE membership.organization_id=? AND membership.status='ACTIVE' AND membership.role IN ('OWNER','MANAGER','SALES') ORDER BY user.name`).bind(context.organizationId).all() : { results: [] };
  let commercial = null, tasks = null, agenda = null, finance = null;
  if (visibility.commercial) {
    const [newLeads, open, pipeline, proposals, closed, stages] = await Promise.all([
      env.DB.prepare(`SELECT COUNT(*) AS count FROM opportunities opportunity WHERE ${opportunityWhere} AND opportunity.stage='NEW'`).bind(...opportunityBindings).first<CountRow>(),
      env.DB.prepare(`SELECT COUNT(*) AS count FROM opportunities opportunity WHERE ${opportunityWhere} AND opportunity.stage NOT IN ('CLOSED_WON','CLOSED_LOST')`).bind(...opportunityBindings).first<CountRow>(),
      env.DB.prepare(`SELECT COALESCE(SUM(opportunity.proposed_value),0) AS total FROM opportunities opportunity WHERE ${opportunityWhere} AND opportunity.stage NOT IN ('CLOSED_WON','CLOSED_LOST')`).bind(...opportunityBindings).first<CountRow>(),
      env.DB.prepare(`SELECT COUNT(*) AS count FROM proposals proposal JOIN opportunities opportunity ON opportunity.id=proposal.opportunity_id AND opportunity.organization_id=proposal.organization_id WHERE proposal.organization_id=? AND date(proposal.created_at)>=? AND date(proposal.created_at)<=? AND proposal.status IN ('DRAFT','SENT')${artistId ? " AND proposal.artist_id=?" : ""}${commercialId ? " AND opportunity.assigned_user_id=?" : ""}`).bind(...opportunityBindings).first<CountRow>(),
      env.DB.prepare(`SELECT COUNT(*) AS count FROM shows show JOIN opportunities opportunity ON opportunity.id=show.opportunity_id AND opportunity.organization_id=show.organization_id WHERE show.organization_id=? AND date(show.created_at)>=? AND date(show.created_at)<=?${artistId ? " AND show.artist_id=?" : ""}${commercialId ? " AND opportunity.assigned_user_id=?" : ""}`).bind(...opportunityBindings).first<CountRow>(),
      env.DB.prepare(`SELECT opportunity.stage,COUNT(*) AS count FROM opportunities opportunity WHERE ${opportunityWhere} GROUP BY opportunity.stage ORDER BY count DESC`).bind(...opportunityBindings).all(),
    ]);
    commercial = { newLeads: newLeads?.count || 0, openOpportunities: open?.count || 0, pipelineValue: pipeline?.total || 0, openProposals: proposals?.count || 0, closedShows: closed?.count || 0, stages: stages.results };
  }
  if (visibility.agenda) {
    const salesShow = commercialId ? " AND opportunity.assigned_user_id=?" : "", showBindings = [context.organizationId, window.operationalStart, window.operationalEnd, ...(artistId ? [artistId] : []), ...(commercialId ? [commercialId] : [])];
    const calendarSales = commercialId ? " AND opportunity.assigned_user_id=?" : "", calendarBindings = [context.organizationId, `${window.operationalStart}T00:00`, `${window.operationalEnd}T23:59`, ...(artistId ? [artistId] : []), ...(commercialId ? [commercialId] : [])];
    const [shows, options, blocks] = await Promise.all([
      env.DB.prepare(`SELECT show.id,show.event_name AS title,show.date,show.show_time AS time,show.city,show.state,artist.name AS artistName FROM shows show JOIN artists artist ON artist.id=show.artist_id AND artist.organization_id=show.organization_id JOIN opportunities opportunity ON opportunity.id=show.opportunity_id AND opportunity.organization_id=show.organization_id WHERE show.organization_id=? AND show.date>=? AND show.date<=? AND show.status IN ('CONFIRMED','IN_PREPARATION')${artistId ? " AND show.artist_id=?" : ""}${salesShow} ORDER BY show.date,show.show_time LIMIT 6`).bind(...showBindings).all(),
      env.DB.prepare(`SELECT entry.id,entry.title,entry.start_datetime AS startDatetime,artist.name AS artistName FROM calendar_entries entry JOIN artists artist ON artist.id=entry.artist_id AND artist.organization_id=entry.organization_id LEFT JOIN opportunity_calendar_entries link ON link.calendar_entry_id=entry.id AND link.organization_id=entry.organization_id LEFT JOIN opportunities opportunity ON opportunity.id=link.opportunity_id AND opportunity.organization_id=link.organization_id WHERE entry.organization_id=? AND entry.start_datetime>=? AND entry.start_datetime<=? AND entry.status='OPTION'${artistId ? " AND entry.artist_id=?" : ""}${calendarSales} ORDER BY entry.start_datetime LIMIT 6`).bind(...calendarBindings).all(),
      env.DB.prepare(`SELECT entry.id,entry.title,entry.start_datetime AS startDatetime,artist.name AS artistName FROM calendar_entries entry JOIN artists artist ON artist.id=entry.artist_id AND artist.organization_id=entry.organization_id LEFT JOIN opportunity_calendar_entries link ON link.calendar_entry_id=entry.id AND link.organization_id=entry.organization_id LEFT JOIN opportunities opportunity ON opportunity.id=link.opportunity_id AND opportunity.organization_id=link.organization_id WHERE entry.organization_id=? AND entry.start_datetime>=? AND entry.start_datetime<=? AND entry.status='BLOCKED'${artistId ? " AND entry.artist_id=?" : ""}${calendarSales} ORDER BY entry.start_datetime LIMIT 6`).bind(...calendarBindings).all(),
    ]); agenda = { upcomingShows: shows.results, options: options.results, blocks: blocks.results };
  }
  if (visibility.tasks) {
    const taskWhere = `opportunity.organization_id=? AND opportunity.stage NOT IN ('CLOSED_WON','CLOSED_LOST')${artistId ? " AND opportunity.artist_id=?" : ""}${commercialId ? " AND opportunity.assigned_user_id=?" : ""}`, taskBindings = [context.organizationId, ...operationalBindings];
    const [stale, overdueActions, todayActions, optionAttention] = await Promise.all([
      env.DB.prepare(`SELECT opportunity.id,customer.name AS customerName,artist.name AS artistName,COALESCE(MAX(activity.created_at),opportunity.created_at) AS lastInteraction FROM opportunities opportunity JOIN customers customer ON customer.id=opportunity.customer_id AND customer.organization_id=opportunity.organization_id JOIN artists artist ON artist.id=opportunity.artist_id AND artist.organization_id=opportunity.organization_id LEFT JOIN opportunity_activities activity ON activity.opportunity_id=opportunity.id AND activity.organization_id=opportunity.organization_id WHERE ${taskWhere} GROUP BY opportunity.id HAVING datetime(lastInteraction)<datetime('now','-7 days') ORDER BY lastInteraction LIMIT 6`).bind(...taskBindings).all(),
      env.DB.prepare(`SELECT opportunity.id,opportunity.next_action AS nextAction,opportunity.next_action_at AS nextActionAt,customer.name AS customerName,artist.name AS artistName FROM opportunities opportunity JOIN customers customer ON customer.id=opportunity.customer_id AND customer.organization_id=opportunity.organization_id JOIN artists artist ON artist.id=opportunity.artist_id AND artist.organization_id=opportunity.organization_id WHERE ${taskWhere} AND opportunity.next_action IS NOT NULL AND date(opportunity.next_action_at)<date('now') ORDER BY opportunity.next_action_at LIMIT 6`).bind(...taskBindings).all(),
      env.DB.prepare(`SELECT opportunity.id,opportunity.next_action AS nextAction,opportunity.next_action_at AS nextActionAt,customer.name AS customerName,artist.name AS artistName FROM opportunities opportunity JOIN customers customer ON customer.id=opportunity.customer_id AND customer.organization_id=opportunity.organization_id JOIN artists artist ON artist.id=opportunity.artist_id AND artist.organization_id=opportunity.organization_id WHERE ${taskWhere} AND opportunity.next_action IS NOT NULL AND date(opportunity.next_action_at)=date('now') ORDER BY opportunity.next_action_at LIMIT 6`).bind(...taskBindings).all(),
      env.DB.prepare(`SELECT entry.id,entry.title,entry.start_datetime AS startDatetime,artist.name AS artistName FROM calendar_entries entry JOIN artists artist ON artist.id=entry.artist_id AND artist.organization_id=entry.organization_id LEFT JOIN opportunity_calendar_entries link ON link.calendar_entry_id=entry.id AND link.organization_id=entry.organization_id LEFT JOIN opportunities opportunity ON opportunity.id=link.opportunity_id AND opportunity.organization_id=link.organization_id WHERE entry.organization_id=? AND entry.status='OPTION' AND entry.start_datetime>=datetime('now') AND entry.start_datetime<=datetime('now','+14 days')${artistId ? " AND entry.artist_id=?" : ""}${commercialId ? " AND opportunity.assigned_user_id=?" : ""} ORDER BY entry.start_datetime LIMIT 6`).bind(context.organizationId, ...operationalBindings).all(),
    ]); tasks = { stale: stale.results, overdueActions: overdueActions.results, todayActions: todayActions.results, optionAttention: optionAttention.results };
  }
  if (visibility.finance) {
    const financeBindings = [context.organizationId, ...(artistId ? [artistId] : [])], artistClause = artistId ? " AND show.artist_id=?" : "";
    const [overdue, upcoming] = await Promise.all([
      env.DB.prepare(`SELECT payment.id,payment.description,payment.amount,payment.due_date AS dueDate,show.event_name AS showName,artist.name AS artistName FROM payments payment JOIN shows show ON show.id=payment.show_id AND show.organization_id=payment.organization_id JOIN artists artist ON artist.id=show.artist_id AND artist.organization_id=show.organization_id WHERE payment.organization_id=? AND payment.status IN ('PENDING','OVERDUE') AND payment.due_date<date('now')${artistClause} ORDER BY payment.due_date LIMIT 6`).bind(...financeBindings).all(),
      env.DB.prepare(`SELECT payment.id,payment.description,payment.amount,payment.due_date AS dueDate,show.event_name AS showName,artist.name AS artistName FROM payments payment JOIN shows show ON show.id=payment.show_id AND show.organization_id=payment.organization_id JOIN artists artist ON artist.id=show.artist_id AND artist.organization_id=show.organization_id WHERE payment.organization_id=? AND payment.status='PENDING' AND payment.due_date>=date('now') AND payment.due_date<=date('now','+7 days')${artistClause} ORDER BY payment.due_date LIMIT 6`).bind(...financeBindings).all(),
    ]); finance = { overdue: overdue.results, upcoming: upcoming.results };
  }
  return Response.json({ role: context.membership.role, period, window, filters: { artists: artists.results, commercials: commercials.results, selectedArtist: artistId, selectedCommercial: commercialId }, visibility, commercial, agenda, tasks, finance });
}
